# Generated by Django 2.2 on 2019-04-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_longue', models.URLField(unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('pseudo_createur', models.CharField(max_length=100)),
                ('nombre_acces', models.IntegerField(default=0)),
            ],
        ),
    ]
