# Generated by Django 2.2 on 2019-04-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniurl',
            name='pseudo_createur',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
