# Generated by Django 2.2 on 2019-04-26 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Visible'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contenu', models.CharField(max_length=500)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Visible')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.Article')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
