# Generated by Django 2.2 on 2019-04-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190426_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
