# Generated by Django 2.2 on 2019-04-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Categorie'),
        ),
    ]
